[package]
name = "sazan"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.24"
zip = { version = "0.6", default-features = false, features = ["deflate"] }
flate2 = { version = "1.0", default-features = false, features = ["rust_backend"] }
